@startgantt
' Sample content from https://d33wubrfki0l68.cloudfront.net/85975663ee3d10baa062c8406db6c5f10627a601/0a978/images/chart-title.png
Project starts on 23 July 2016
[Task 1] as [1] lasts 5 days
[Task 2] as [2] lasts 6 days and starts 1 day after [1]'s start
[Task 3] as [3] lasts 9 days and starts 1 day after [1]'s start
[Task 4] as [4] lasts 11 days and starts 1 day after [1]'s start
[Phase 1 completed] happens at [4]'s end
[Task 5] as [5] lasts 11 days and starts 4 days after [4]'s start
[Task 6] as [6] lasts 6 days and starts 4 days after [4]'s start
[Task 7] as [7] lasts 13 days and starts 3 days after [6]'s start
[Phase 2 completed] happens at [7]'s end
[Task 8] as [8] lasts 10 days and starts 4 days after [7]'s start
[Task 9] as [9] lasts 5 days and starts 4 days after [7]'s start
[Phase 3 completed] happens at [8]'s end

[1] is colored in LightBlue
[2] is colored in LightBlue
[3] is colored in LightBlue
[4] is colored in LightBlue
[5] is colored in Teal
[6] is colored in Teal
[7] is colored in Teal
[8] is colored in Orchid
[9] is colored in Orchid
@endgantt
